### PR TITLE
Sensitivity Options Implemented

### PR DESCRIPTION
**Pull request by Kevin-Insinna**
## Summarize what is being added
-Sensitivity Options are fully functional within the settings menu both on the Title Screen and in game.

## Please describe how to test
-Open the game in the Title Scene and change some of the settings (NOTE: Sensitivity setting when using mouse only affects the Crosshair, not the mouse cursor)
-Start the game and test the sensitivity of the crosshair to see how the different options feel
-Test the changes again with the other input method
-Settings for sensitivity should persist between scenes and play sessions, as long as they are applied when changed. 

## Relevant Screenshots
image

## Issue worked on
[](https://bat-bots.atlassian.net/jira/software/projects/BB/boards/1?selectedIssue=BB-34)

## What Sprint is this due in?
Sprint 1

### CODE REVIEW

**Review by RitoxicGame — COMMENTED** [review]
reviewing now, quick comment BEFORE I forget:

intuitively, I want to be able to close out of the options menu with Circle. In general, being able to cancel out of the menu without saving options would be nice, but I don't know if there's a way to do that on controller right now.

**Review by RitoxicGame — COMMENTED** [review]
Controller sensitivity seems a bit high, even at base level, but that may just be me

**Review by RitoxicGame — CHANGES_REQUESTED** [review]
Needs to go int to dev and not main!

**Review by RitoxicGame — COMMENTED** [review]
One more quick thing: it seems like mouse sensitivity defaulted to 0 before I fiddled with it in the options menu. At the very least, I was unable to move the cursor until I changed the sensitivity. It still let me shoot bats, so it wasn't a mouse issue.

I want to verify this by deleting/resetting my playerprefs, but I can't find the directory where they're supposedly stored ;u;

**Review by RitoxicGame — COMMENTED** [review]
ONE MORE THING 😭:
you might need to hold off on merging this for a bit.

There seems to be an issue on this branch where quitting to the title screen and then re-entering the game scene deletes the BatStateMachine, causing all bats to become uninteractable.

Unfortunately, when I went to double-check if this issue was present on dev, a *separate* bug made me unable to verify whether or not this one is branch-specific. As such, regardless of whether or not this issue is already fixed on dev, rebasing currently doesn't seem like a good idea.

**Comment by ArgentumRhodon** [comment]
I agree with Quinn, that interactivity bug is a major issue, though I'm not sure it is an issue on this branch as dev is also bugged. Perhaps we could merge this branch and fix those issues in another. We'll have to see tomorrow.

**Review by RitoxicGame — COMMENTED** [review]
Two things copied over from chat:

First and foremost, the cancel doesn't appear to be working. It neither closes the menu nor resets the settings.

Second (and much more subjectively), sensitivity level 2.0 feels great for joystick but nearly uncontrollable for mouse. I definitely agree with the decision to merge the two into one option, but I feel like baseline mouse sensitivity should be adjusted to align the two.

That said, that last thing can probably be a separate PR.
Again, very sorry for gumming up the works earlier.

**Comment by Kevin-Insinna** [comment]
> Two things copied over from chat:
> 
> First and foremost, the cancel doesn't appear to be working. It neither closes the menu nor resets the settings.
> 
> Second (and much more subjectively), sensitivity level 2.0 feels great for joystick but nearly uncontrollable for mouse. I definitely agree with the decision to merge the two into one option, but I feel like baseline mouse sensitivity should be adjusted to align the two.
> 
> That said, that last thing can probably be a separate PR. Again, very sorry for gumming up the works earlier.

Fixed the first issue. I agree that the sensitivity is probably subjective and might be worth dealing with in a future PR. Considering that players using a mouse will also being using different DPI settings it's hard to pinpoint a solid range that would satisfy everyone. Something to balance and mess with down the line.

**Pull request merged**
